// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    GameCard: typeof import('./components/GameCard.vue')['default']
    GameHeader: typeof import('./components/GameHeader.vue')['default']
    GameList: typeof import('./components/GameList.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    Money: typeof import('./components/money.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
